#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSIC
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PSIC_DB")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PSIC_DBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_cssMenu")]
		public ISingleResult<sp_cssMenuResult> sp_cssMenu([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Emp_Id", DbType="Int")] System.Nullable<int> emp_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), emp_Id);
			return ((ISingleResult<sp_cssMenuResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_cssMenuSub")]
		public ISingleResult<sp_cssMenuSubResult> sp_cssMenuSub([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Module_ID", DbType="Int")] System.Nullable<int> module_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_Group_Id", DbType="Int")] System.Nullable<int> user_Group_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), module_ID, user_Group_Id);
			return ((ISingleResult<sp_cssMenuSubResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_cssMenuResult
	{
		
		private int _Module_Id;
		
		private string _Module_Name;
		
		private System.Nullable<int> _Priority;
		
		private int _User_Group_Id;
		
		public sp_cssMenuResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Module_Id", DbType="Int NOT NULL")]
		public int Module_Id
		{
			get
			{
				return this._Module_Id;
			}
			set
			{
				if ((this._Module_Id != value))
				{
					this._Module_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Module_Name", DbType="VarChar(426)")]
		public string Module_Name
		{
			get
			{
				return this._Module_Name;
			}
			set
			{
				if ((this._Module_Name != value))
				{
					this._Module_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="Int")]
		public System.Nullable<int> Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this._Priority = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Group_Id", DbType="Int NOT NULL")]
		public int User_Group_Id
		{
			get
			{
				return this._User_Group_Id;
			}
			set
			{
				if ((this._User_Group_Id != value))
				{
					this._User_Group_Id = value;
				}
			}
		}
	}
	
	public partial class sp_cssMenuSubResult
	{
		
		private string _Column1;
		
		public sp_cssMenuSubResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="VarChar(MAX)")]
		public string Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
